server:
  port: 8086

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: resource-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  eureka:
    instance:
      instance-id: resource-server

    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resource?serverTimezone=Asia/Seoul
    username: resource
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

cloud:
  aws:
    credentials:
      accessKey: AKIAZJT74GBIBDSCEMNP
      secretKey: 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
    s3:
      bucket: mztalk-resource-server    # ex) marryting-gyunny
      dir: /image
    region:
      static: ap-northeast-2
    stack:
      auto: false


